# Directory of mzML files
data_dir : 'data'

# Database directory
database_dir : 'reference'
db_filename_1 : 'NPS DB-240214.csv'
db_filename_2 : 'Training_Database_with_fbs_rt.csv'

# Output directory of the data
output_dir : 'output/ms_data/expedited_2023/'

