# This config file hosts the variable names, lists and column identifiers for the nps script
# Variable Names
model_index : 'Name' # Sample ID ['Compound', 'Name']
test_model_index : 'Compound'
model_y : 'Retention Time (min)'  #['PTC Confirmed RT', 'Retention Time (min)']
test_model_y : 'PTC Confirmed RT'
model_X : 'SMILES'
# Column Names
lab_column_name : 'LAB'

## Filepaths

# Create Dataset
working_dir : '/arc/project/st-ashapi01-1/git/afraz96/RADD/workflows/part2_version2'
raw_data_dir : 'Data'
output_dir : 'Data'
linking_dir : 'output'
# ML pipeline
default_output_dir : 'output'
model_names : ['CatBoost', 'Lasso', 'LGBM', 'Neural Network','Random Forest', 'XGBoost'] 
## Filenames
raw_data_filename : 'NEW_X500R_SMILES.csv'
smiles_dict_filename : 'smiles_dict.pkl'
output_filename : 'NEW_X500R_SMILES.csv'
